--- 
- hosts: all
  become: yes
  connection: ssh
  gather_facts: yes
  tasks: 
    - name: configure Docker 
      yum_repository: 
       baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    - name: Docker Package
      package:
       name:
       - "docker-ce-18.09.1-3.el7.x86_64"
       state: present
    - name: Start and Enable the Services
      service:
       name: docker
       state: started
       enable: yes
    - name: Installing docker sdk for python3
      command: pip3 install docker     
