--- 
- hosts: all
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
    - name: Add Signing Key 
      ansible.builtin.rpm_key:
        key: "https://download.docker.com/linux/centos/gpg"
        state: present
    - name: Add repository
      ansible.builtin.yum_repository:
        name: Docker
        description: docker repository
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable"
        enabled: true
        gpgcheck: true
        gpgkey: "https://download.docker.com/linux/centos/gpg"
    - name: Install Package
      ansible.builtin.package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
    - name: start and enable docker
      ansible.builtin.service:
        name: docker
        enabled: yes
        state: started      
    - name: Create a folder
      file: 
       path: "/var/www/tasks/"
       state: directory
    - name: copy content on managed node 
      copy: 
       content: "Welcome to the task-1"
       dest: "/var/www/tasks/index.html"
    - name: create httpd container
      docker_container:
       name: myserver
       image: httpd
       ports: 
       - "80"
       volumes:
        - /var/www/tasks/index.html:/usr/local/apache2/htdocs/ 
  
